### PR TITLE
Bring Go version to 1.12.5

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
@radekg please review

**Comment by radekg** [comment]
Hi @gliptak. Thank you for the PR. I see that golang 1.12.5 is now the most recent. Do you think it's a good idea to use the most recent one?

**Comment by gliptak** [comment]
@radekg updated to ```1.12.6```

**Comment by radekg** [comment]
Merged. Thank you for contributing this. Thank you for the patience.

**Pull request merged**
