### PR TITLE
Add backward compatibility with previous Terraform versions

### PR DESCRIPTION
**Pull request by cryptobioz**
This PR adds backward compatibility with previous versions of Terraform (0.11 tested).

The code is not very clean and might be improved but I can't really understand what's going wrong with these interfaces.

### CODE REVIEW

**Comment by mcanevet** [comment]
@radekg what prevent this PR to be merged?

**Comment by radekg** [comment]
Hi @mcanevet, nothing prevented it from being merged other than a lack of time to run tests properly.

**Comment by cryptobioz** [comment]
Thanks @radekg!

**Comment by radekg** [comment]
Thank you, @cryptobioz. I will do a release tonight.

**Pull request merged**
