### PR TITLE
[WIP] address #101 add `extra_vars_json`

### PR DESCRIPTION
**Pull request by sjwl**
### Summary
Add complex variable support by adding `extra_vars_json`.  Addresses #101

### CODE REVIEW

**Comment by sjwl** [comment]
This is functional, but still WIP, since I'd like to update the README once I do more testing.

**Comment by radekg** [comment]
This is shaping up really nice. Looking forward to a complete pr! Please let me know if I can help in any way.

**Comment by sjwl** [comment]
@radekg I've updated the docs, but also added a couple more features:
1) made it work for terraform v0.12  (tested with alpha2)
2) added `global_plays` see docs

**Comment by radekg** [comment]
Hi @sjwl, apologies for such a long period of inactivity regarding this PR. A couple of reasons: it's a fairly busy period of time over the last few months. Second, the PR mixes a couple of things:

- there's the feature itself
- it updates the master to terraform 0.12 alpha version, which I would like to avoid

I would be happy to take the feature in, without the terraform 0.12 upgrade. Terraform 0.12 should be definitely taken into consideration, but that should stay on a separate branch until Terraform 0.12 is released.

**Pull request closed without merging**
