### PR TITLE
Add root module configuration for compatibility with the registry

### PR DESCRIPTION
**Pull request by adamwg**
Currently if you try to use this plugin as a module (by adding a `module` stanza to a `.tf` file and running `terraform init`) you'll get an error like this one:

```
Error downloading modules: Error loading modules: module ansible:
No Terraform configuration files found in directory:
.terraform/modules/efa9ea92b00a7d9a390c76925473b230/radekg-terraform-provisioner-ansible-64ae1a8
```

I believe what's missing are the `.tf` files that comprise the "root configuration", which for this module can be empty.

### CODE REVIEW

**Comment by adamwg** [comment]
@radekg Not sure how to test this change... I suspect it requires creating a test version for the registry to pick up and then trying to use it from a `module` stanza. Let me know if there's some way I can test it, or if you can take care of it :-).

**Comment by radekg** [comment]
Hi @adamwg, I'm not sure if the desired result of `init` with such stanza is what one would expect.

Yes, the files are for sure missing, but I think the `init` will not install a `provisioner` anyway. It simply pulls a git repo into the modules directory, it does not fetch the actual binary.

```
[rad] local-no-bastion (master) $ ls -la .terraform/modules/efa9ea92b00a7d9a390c76925473b230/radekg-terraform-provisioner-ansible-64ae1a8/
total 184
drwxr-xr-x  21 rad  staff    672 Oct 12 00:01 .
drwxr-xr-x   3 rad  staff     96 Oct 21 14:08 ..
drwxr-xr-x   4 rad  staff    128 Oct 12 00:01 .github
-rw-rw-r--   1 rad  staff    125 Oct 12 00:01 .gitignore
-rw-rw-r--   1 rad  staff    102 Oct 12 00:01 .travis.yml
-rw-rw-r--   1 rad  staff      6 Oct 12 00:01 .version
-rw-rw-r--   1 rad  staff   3217 Oct 12 00:01 CODE_OF_CONDUCT.md
-rw-rw-r--   1 rad  staff    815 Oct 12 00:01 CONTRIBUTING.md
-rw-rw-r--   1 rad  staff  11356 Oct 12 00:01 LICENSE
-rw-rw-r--   1 rad  staff   1444 Oct 12 00:01 Makefile
-rw-rw-r--   1 rad  staff  20394 Oct 12 00:01 README.md
drwxr-xr-x   7 rad  staff    224 Oct 12 00:01 bin
drwxr-xr-x   9 rad  staff    288 Oct 12 00:01 examples
-rw-rw-r--   1 rad  staff   8559 Oct 12 00:01 glide.lock
-rw-rw-r--   1 rad  staff    423 Oct 12 00:01 glide.yaml
-rw-rw-r--   1 rad  staff    251 Oct 12 00:01 main.go
drwxr-xr-x  11 rad  staff    352 Oct 12 00:01 mode
-rw-rw-r--   1 rad  staff   3804 Oct 12 00:01 resource_provisioner.go
-rw-rw-r--   1 rad  staff   8570 Oct 12 00:01 resource_provisioner_test.go
drwxr-xr-x  10 rad  staff    320 Oct 12 00:01 types
drwxr-xr-x   5 rad  staff    160 Oct 12 00:01 vendor
```

**Comment by radekg** [comment]
To clarify, this has nothing to do with the PR. The issue(s):

- it doesn't look like `init` handles provisioners
- `module` isn't the correct method for distributing provisioners

It might be a good idea to stick it in the readme, https://github.com/radekg/terraform-provisioner-ansible#installation, maybe?

**Comment by adamwg** [comment]
Aha, interesting. I was thinking that modules provided a way to automatically download the provisioner, like `provider` stanzas, but re-reading the docs I see that doesn't appear to be the case. Happy to close this and document the installation instead.

I also have a dockerfile that adds ansible and the provisioner to `hashicorp/terraform:light`, giving a consistent environment for everyone on my team to use for updating our terraform+ansible-managed infrastructure. I could add that here as well, and you could publish the container to the docker registry as an easy way to use terraform+ansible. What do you think?

**Pull request closed without merging**
