### PR TITLE
[WIP] Add support of Terraform v0.12

### PR DESCRIPTION
**Pull request by cryptobioz**

### CODE REVIEW

**Comment by radekg** [comment]
Hi @cryptobioz. Thank you! Definitely. Please let me get the https://github.com/radekg/terraform-provisioner-ansible/pull/124 in and I'll be on this before the end of the weekend. I should properly plan for future 0.11.x updates.

**Comment by nicholasamorim** [comment]
How is this looking? I see #124 has been merged.

**Comment by alexkreidler** [comment]
We're all waiting on this!! 

We love this project, but we need support for terraform 0.12. Thanks!

**Comment by systembell** [comment]
@alexkreidler I second it. I've got it working in 0.12 with @ivandeex's release on his fork in the meantime. Works perfectly.

**Comment by ivandeex** [comment]
This patch makes the plugin work in 0.12 but breaks compatibility with 0.11, because validation function works directly with internal packer structures. I made a better patch, which uses packer API instead. The patched plugin is compatible with both pre- and post-0.12 packer versions. Unfortunately I was too busy to submit last week.

**Comment by systembell** [comment]
I didn't have any issues @ivandeex because I'd converted everything to 0.12. Thanks a ton for your releases!

**Comment by jakubgs** [comment]
Holy Vendor Batman! 8267 files changed...
This is why God invented lock files like `go.mod` and `go.sum` on the 8th day.
Thanks a bunch for your work!

**Comment by jakubgs** [comment]
How do I build this? I've cloned your repo but when i run `build-linux` I'm getting:
```
./bin/check-golang-version.sh
mkdir -p ~/.terraform.d/plugins
CGO_ENABLED=0 GOOS=linux installsuffix=cgo go build -o ./terraform-provisioner-ansible-linux
# _/home/sochan/soft/terraform-provisioner-ansible-fixed
./resource_provisioner.go:25:4: cannot use types.NewPlaySchema() (type *"github.com/radekg/terraform-provisioner-ansible/vendor/github.com/hashicorp/terraform/helper/schema".Schema) as type *"github.com/hashicorp/terraform/helper/schema".Schema in map value
./resource_provisioner.go:26:4: cannot use types.NewDefaultsSchema() (type *"github.com/radekg/terraform-provisioner-ansible/vendor/github.com/hashicorp/terraform/helper/schema".Schema) as type *"github.com/hashicorp/terraform/helper/schema".Schema in map value
./resource_provisioner.go:27:4: cannot use types.NewRemoteSchema() (type *"github.com/radekg/terraform-provisioner-ansible/vendor/github.com/hashicorp/terraform/helper/schema".Schema) as type *"github.com/hashicorp/terraform/helper/schema".Schema in map value
./resource_provisioner.go:28:4: cannot use types.NewAnsibleSSHSettingsSchema() (type *"github.com/radekg/terraform-provisioner-ansible/vendor/github.com/hashicorp/terraform/helper/schema".Schema) as type *"github.com/hashicorp/terraform/helper/schema".Schema in map value
./resource_provisioner.go:107:40: cannot use s (type *"github.com/hashicorp/terraform/terraform".InstanceState) as type *"github.com/radekg/terraform-provisioner-ansible/vendor/github.com/hashicorp/terraform/terraform".InstanceState in argument to mode.NewRemoteMode
./resource_provisioner.go:115:37: cannot use s (type *"github.com/hashicorp/terraform/terraform".InstanceState) as type *"github.com/radekg/terraform-provisioner-ansible/vendor/github.com/hashicorp/terraform/terraform".InstanceState in argument to mode.NewLocalMode
make: *** [Makefile:43: build-linux] Error 2
```

**Comment by radekg** [comment]
PR https://github.com/radekg/terraform-provisioner-ansible/pull/129 replaces this one. https://github.com/radekg/terraform-provisioner-ansible/pull/129 upgrades Terraform to 0.12.5, fixes tests, updates examples to work with Terraform 0.12.x.

**Pull request closed without merging**
